# Generated by Django 4.2.20 on 2025-03-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
    ]
