# Generated by Django 4.2.20 on 2025-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_inventory', '0002_supplier_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='اسم المحل')),
                ('commercial_register', models.CharField(max_length=50, verbose_name='السجل التجاري')),
                ('tax_number', models.CharField(max_length=50, verbose_name='البطاقة الضريبية')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='شعار المحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المحل',
                'verbose_name_plural': 'إعدادات المحل',
            },
        ),
    ]
