# Generated by Django 4.2.20 on 2025-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_inventory', '0003_storesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='compatible_cars',
            field=models.ManyToManyField(blank=True, related_name='compatible_parts', to='parts_inventory.carmodel', verbose_name='السيارات المتوافقة'),
        ),
    ]
