# Generated by Django 4.2.20 on 2025-03-25 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts_inventory', '0005_part_purchase_price_alter_part_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء'), ('adjustment_add', 'إضافة يدوية'), ('adjustment_subtract', 'خصم يدوي'), ('return_in', 'مرتجع وارد'), ('return_out', 'مرتجع صادر')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('previous_quantity', models.IntegerField(verbose_name='الكمية السابقة')),
                ('current_quantity', models.IntegerField(verbose_name='الكمية الحالية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المرجع')),
                ('reference_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='parts_inventory.part', verbose_name='قطعة الغيار')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
    ]
